// Copyright (c) Choreo contributors

// Auto-generated by update_field_dimensions.py

#pragma once

#include <units/length.h>

namespace choreo::util {
static constexpr units::meter_t fieldLength = 17.1507912_m;
static constexpr units::meter_t fieldWidth = 8.0692752_m;
}  // namespace choreo::util
