// Copyright (c) Choreo contributors

// Auto-generated by update_field_dimensions.py
#pragma once
#include <wpi/units/length.hpp>

namespace choreo::util {
static constexpr wpi::units::meter_t fieldLength = 17.548_m;
static constexpr wpi::units::meter_t fieldWidth = 8.052_m;
}  // namespace choreo::util
